<template><view class="page"><view class="header"><view><text class="title">曲目管理</text><text class="copy">{{ hint }}</text></view><button class="refresh" :disabled="receiving" @click="refresh">刷新</button></view><view class="current"><text>当前曲目</text><text>{{ currentSongName }}</text></view><button class="create" :disabled="receiving || deletingId !== null" @click="createSong">新建我的曲谱</button><view v-if="songs.length"><view v-for="song in songs" :key="song.id" class="card" :class="{ active: song.id === selectedId }" @click="selectSong(song)"><view><text class="song-name">{{ song.name }}</text><text class="song-id">{{ songKind(song.id) }} · ID {{ song.id }}</text></view><button v-if="song.id >= 16" class="delete" :disabled="deletingId !== null" @click.stop="deleteSong(song)">{{ deletingId === song.id ? '删除中' : '删除' }}</button><text v-else>{{ song.id === selectedId ? '当前使用中' : '切换' }}</text></view></view><view v-else class="empty">{{ disconnected ? '蓝牙已断开' : receiving ? '正在读取内置曲目…' : '暂无曲目' }}</view><text v-if="!receiving" class="count">共 {{ songs.length }} 首内置曲目</text></view></template>
<script>
import spp from '../../services/spp.js'
export default { data() { return { songs: [], selectedId: null, receiving: false, selectingId: null, deletingId: null, disconnected: false, hint: '读取开发板曲目', unsubscribe: null } }, computed: { currentSongName() { const song = this.songs.find((item) => item.id === this.selectedId); return song ? song.name : '正在读取…' } }, onShow() { this.unsubscribe = spp.subscribe(this.onSppEvent); this.refresh() }, onHide() { if (this.unsubscribe) this.unsubscribe() }, methods: {
songKind(id) { return id < 16 ? '内置曲目' : '我的曲目' }, createSong() { uni.navigateTo({ url: '/pages/song-editor/song-editor' }) }, refresh() { if (!spp.socket) { this.disconnected = true; this.hint = '请先连接 JDY-31-SPP'; return } this.disconnected = false; this.songs = []; this.receiving = true; spp.send('M2,SONGS\n') },
onSppEvent(event) { if (event.type === 'status' && event.state !== '已连接') { this.disconnected = true; this.receiving = false; this.selectingId = null; this.deletingId = null; return } if (event.type !== 'frame') return; const f = event.frame; if (f.type === 'mode2_select_ok' && f.id === this.selectingId) { this.selectingId = null; this.selectedId = f.id; uni.showToast({ title: `已切换为 ${this.currentSongName}`, icon: 'success' }); return } if (f.type === 'mode2_song_delete_ok' && f.songId === this.deletingId) { this.deletingId = null; uni.showToast({ title: '已删除', icon: 'success' }); this.refresh(); return } if (f.type === 'mode2_error' && this.selectingId !== null) { this.selectingId = null; uni.showToast({ title: f.reason === 'BUSY' ? '当前挑战正在进行，请结束后再切换' : '切换失败', icon: 'none' }); return } if (f.type === 'mode2_error' && this.deletingId !== null) { this.deletingId = null; uni.showToast({ title: f.reason === 'READONLY' ? '内置曲目不可删除' : '删除失败', icon: 'none' }); return } if (!this.receiving) return; if (f.type === 'mode2_songs') this.selectedId = f.selectedId; if (f.type === 'mode2_song') this.songs.push(f); if (f.type === 'mode2_end') { this.receiving = false; this.hint = `共 ${this.songs.length} 首曲目` } },
selectSong(song) { if (!song || song.id === this.selectedId || this.selectingId !== null || this.deletingId !== null) return; uni.showModal({ title: '切换曲目', content: `确认切换为 ${song.name}？`, success: (r) => { if (!r.confirm) return; this.selectingId = song.id; if (!spp.send(`M2,SELECT,${song.id}\n`)) { this.selectingId = null; uni.showToast({ title: '切换失败，请重新连接', icon: 'none' }) } } }) },
deleteSong(song) { if (!song || song.id < 16 || this.deletingId !== null) return; uni.showModal({ title: '删除曲目', content: `确认删除 ${song.name}？`, success: (r) => { if (!r.confirm) return; this.deletingId = song.id; if (!spp.send(`M2,SONG,DELETE,${song.id}\n`)) { this.deletingId = null; uni.showToast({ title: '删除失败，请重新连接', icon: 'none' }) } } }) }
} }
</script>
<style>.page{min-height:100vh;padding:36rpx;background:#161424;color:#f8f6ff;box-sizing:border-box}.header,.card{display:flex;align-items:center;justify-content:space-between}.header{margin-bottom:24rpx}.title{display:block;font-size:46rpx;font-weight:700}.copy,.song-id{display:block;margin-top:8rpx;color:#aaa5bd;font-size:22rpx}.refresh,.create,.delete{margin:0;border:0;border-radius:16rpx;background:#2b2644;color:#d6c8ff;font-size:23rpx}.refresh::after,.create::after,.delete::after{border:0}.create{width:100%;margin-bottom:20rpx;background:#7654d7;color:#fff}.current,.card{margin-bottom:18rpx;padding:26rpx;background:#211d35;border-radius:22rpx}.current text{display:block}.current text:last-child,.song-name{display:block;margin-top:8rpx;color:#cbb7ff;font-size:30rpx}.active{border:2rpx solid #a976ff}.delete{padding:0 16rpx;color:#ffb9c1;background:#41263b}.empty,.count{display:block;text-align:center;color:#aaa5bd}.empty{margin:160rpx 0}.count{margin:34rpx}</style>
