<template>
	<view class="page">
		<view class="summary"><view><text class="title">第 {{ sequence }} 段演奏</text><text class="copy">录制槽位 {{ slot }} · {{ events.length }} 个音符</text></view><view class="bars"><view v-for="n in 9" :key="n" class="bar" :style="{ height: (18 + (n % 4) * 13) + 'rpx' }"></view></view></view>
		<view class="trace"><text class="trace-title">XY 轨迹可视化</text><canvas canvas-id="trace" class="canvas" :style="{ width: canvasWidth + 'px', height: canvasHeight + 'px' }" :width="canvasWidth" :height="canvasHeight"></canvas><view class="trace-footer"><text>音符数：{{ events.length || expected }}</text><text>记录事件：{{ expected }}</text></view></view>
		<button class="play" @click="togglePlay"><text class="play-icon">{{ playing ? '■' : '▶' }}</text>{{ playing ? '停止播放' : '播放演奏' }}</button>
		<view class="events"><text class="trace-title">事件列表</text><view v-for="(event, index) in events" :key="index" class="event"><text>{{ event.timeMs }} ms</text><text>{{ bands[event.band] }} · {{ notes[event.note] }}</text><text>({{ event.x }}, {{ event.y }})</text></view><view v-if="!events.length" class="waiting">{{ hint }}</view></view>
	</view>
</template>

<script>
	import spp from '../../services/spp.js'
	import * as tone from '../../utils/tone.js'
	export default {
		data() { return { slot: 0, sequence: 0, expected: 0, events: [], hint: '正在读取详情…', playing: false, unsubscribe: null, canvasWidth: 300, canvasHeight: 200, bands: ['低音', '中音', '高音'], notes: ['Do', 'Re', 'Mi', 'Fa', 'Sol', 'La', 'Si'] } },
		onLoad(query) { this.slot = Number(query.slot); this.sequence = Number(query.sequence); this.expected = Number(query.eventCount) },
		onShow() { this.unsubscribe = spp.subscribe(this.onSppEvent); this.setCanvasSize(this.load) },
		onHide() { this.stopPlayback() },
		onUnload() { this.stopPlayback(); if (this.unsubscribe) this.unsubscribe() },
		methods: {
			setCanvasSize(done) { const screenWidth = uni.getSystemInfoSync().windowWidth; this.canvasWidth = Math.floor(screenWidth * (1 - 100 / 750)); this.canvasHeight = Math.round(this.canvasWidth * .64); this.$nextTick(() => done && done.call(this)) },
			load() { if (!spp.socket) { this.hint = '连接已断开，请重新连接'; return } this.events = []; spp.send(`M1,GET,${this.slot}\n`) },
			onSppEvent(event) { if (event.type !== 'frame') return; const frame = event.frame; if (frame.type === 'record') { this.sequence = frame.sequence; this.expected = frame.eventCount } if (frame.type === 'event') this.events.push(frame); if (frame.type === 'end') { this.hint = this.events.length ? '' : '没有事件数据'; this.$nextTick(this.drawTrace) } },
			drawTrace() { const context = uni.createCanvasContext('trace', this); const width = this.canvasWidth, height = this.canvasHeight, margin = Math.max(18, Math.round(width * .075)), stepX = Math.round((width - margin * 2) / 5), stepY = Math.round((height - margin * 2) / 4); context.setFillStyle('#0b0d25'); context.fillRect(0, 0, width, height); context.setStrokeStyle('#302a67'); context.setLineWidth(1); for (let x = margin; x <= width - margin; x += stepX) { context.beginPath(); context.moveTo(x, margin); context.lineTo(x, height - margin); context.stroke() } for (let y = margin; y <= height - margin; y += stepY) { context.beginPath(); context.moveTo(margin, y); context.lineTo(width - margin, y); context.stroke() } context.setStrokeStyle('#7560ca'); context.setLineWidth(2); context.beginPath(); context.moveTo(margin, height - margin); context.lineTo(width - margin, height - margin); context.moveTo(margin, height - margin); context.lineTo(margin, margin); context.stroke(); context.setFillStyle('#d7d0ff'); context.setFontSize(Math.max(12, Math.round(width * .04))); context.fillText('Y', margin - 4, margin - 10); context.fillText('X', width - margin + 6, height - margin + 6); if (!this.events.length) { context.draw(); return } const xs = this.events.map((item) => item.x), ys = this.events.map((item) => item.y); const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys); const point = (event) => ({ x: margin + (event.x - minX) * (width - margin * 2) / (maxX - minX || 1), y: height - margin - (event.y - minY) * (height - margin * 2) / (maxY - minY || 1) }); context.setStrokeStyle('#ad73ff'); context.setLineWidth(Math.max(2, Math.round(width * .008))); this.events.forEach((event, index) => { const xy = point(event); index ? context.lineTo(xy.x, xy.y) : context.moveTo(xy.x, xy.y) }); context.stroke(); this.events.forEach((event) => { const xy = point(event); context.setFillStyle(['#76d7ff', '#d487ff', '#ff9ed8'][event.band] || '#fff'); context.beginPath(); context.arc(xy.x, xy.y, Math.max(4, Math.round(width * .016)), 0, Math.PI * 2); context.fill() }); context.draw() },
			stopPlayback() { tone.stop(); this.playing = false },
			togglePlay() { if (this.playing) return this.stopPlayback(); if (!this.events.length) return; if (!tone.play(this.events, () => { this.playing = false })) { uni.showToast({ title: '当前环境不支持本地音色', icon: 'none' }); return } this.playing = true }
		}
	}
</script>

<style>
	.page { min-height: 100vh; padding: 30rpx 28rpx 52rpx; color: #f8f6ff; background: radial-gradient(circle at 80% 0, #161442, transparent 40%), #070917; box-sizing: border-box; } .summary { display: flex; align-items: center; justify-content: space-between; min-height: 112rpx; padding: 22rpx 24rpx; border: 1rpx solid #5140aa; border-radius: 18rpx; background: linear-gradient(120deg, #1f1542, #101a3d); box-sizing: border-box; } .title { display: block; font-size: 32rpx; font-weight: 700; } .copy { display: block; margin-top: 10rpx; color: #c2bbdb; font-size: 22rpx; } .bars { display: flex; align-items: flex-end; height: 72rpx; gap: 5rpx; } .bar { width: 7rpx; border-radius: 8rpx 8rpx 0 0; background: linear-gradient(#7956ff, #315bdf); box-shadow: 0 0 8rpx #815fff; }
	.trace, .events { margin-top: 24rpx; padding: 22rpx; border: 1rpx solid #4f3bb6; border-radius: 18rpx; background: linear-gradient(135deg, #111334, #10152d); } .trace-title { display: block; margin-bottom: 16rpx; color: #f4efff; font-size: 24rpx; font-weight: 600; } .canvas { display: block; border-radius: 14rpx; background: #0b0d25; } .trace-footer { display: flex; justify-content: space-between; margin: 16rpx 8rpx 0; color: #cbc5dc; font-size: 20rpx; }
	.play { display: flex; align-items: center; justify-content: center; width: 100%; margin-top: 24rpx; border: 1rpx solid #cc67fc; border-radius: 18rpx; color: #fff; font-size: 29rpx; font-weight: 700; line-height: 96rpx; background: linear-gradient(100deg, #5b258e, #3941bf); box-shadow: 0 0 20rpx #7649db55; } .play::after { border: 0; } .play-icon { display: inline-flex; align-items: center; justify-content: center; width: 48rpx; height: 48rpx; margin-right: 16rpx; border: 2rpx solid #dfccff; border-radius: 50%; font-size: 19rpx; line-height: 48rpx; }
	.events { border-color: #2c2c51; } .event { display: flex; justify-content: space-between; padding: 18rpx 0; border-bottom: 1rpx solid #292943; color: #ddd8eb; font-size: 20rpx; } .event:last-child { border: 0; } .waiting { padding: 24rpx 0; color: #aaa5bd; text-align: center; }
</style>
